version: 2.1

jobs:
  oneshot:
    docker:
      - image: node:12.16.3-alpine3.11

    steps:
      - checkout
      - run:
          name: echo test
          command: |
            echo "test"
      - run:
          name: install eslint
          command: |
            npm install -g eslint
      - run:
          name: npm install
          command: |
            npm install
      - run:
          name: npm run lint
          command: |
            npm run lint
workflows:
  version: 2
  node-test:
    jobs:
      - oneshot
