version: 2.1

jobs:
  oneshot:
    machine: true
    steps:
      - checkout
      - run:
          name: echo test
          command: |
            echo "test"
      - run:
          name: npm install
          command: |
            sudo npm install -g prettier eslint
      - run:
          name: npm run lint
          command: |
            npm run lint
workflows:
  version: 2
  node-test:
    jobs:
      - oneshot
